apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox:1.27.2
      command: [ "/bin/sh", "-c", "echo $ENV, $DEBUG && sleep 3600"  ]
      env:
        # Define the environment variable
        - name: ENV
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: env-config
              # Specify the key associated with the value
              key: env
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: env-config
              # Specify the key associated with the value
              key: debug
  restartPolicy: Never
